adminchat:
    allprefix: "&a(&7ALL&a)"
    allmasked: "&3ADMIN"
    allsuffix: ": "

    adminprefix: "&a(&7ADMINS&a)"
    toadminprefix: "&a(&7TO ADMINS&a)"
    adminsuffix: ": "

    usecustomconsolename: true
    customconsolename: "&7[&6CONSOLE&7]"

    listeninchat: true

    rawprefixadmin: "@"
    rawprefixall: "@@"

    notifyonversion: true