adminchat:
    allprefix: "&a(&7ALL&a)"
    allmasked: "&3ADMIN"
    
    adminprefix: "&a(&7ADMINS&a)"
    toadminprefix: "&a(&7TO ADMINS&a)"
    
    usecustomconsolename: true
    customconsolename: "&7[&6CONSOLE&7]"
    
    rawprefix: "@"